[package]
name = "fast-oklch-picker"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_color = { git = "https://github.com/bevyengine/bevy", rev = "5cfcbf4" }
clap = "4.5.17"
eframe = { version = "0.28.1", default-features = false, features = [
	"accesskit",
	"glow",
	"wayland",
	"x11",
	"persistence",
] }
egui_extras = "0.28.1"
enum-map = "2.7.3"
lexical-parse-float = { version = "0.8.5", features = ["format"] }
once_cell = "1.19.0"
regex = "1.10.6"
strum = { version = "0.26.3", features = ["derive"] }
